### ISSUE TITLE
Outdated roadmap and no news in last 2 months

### ISSUE THREAD

**Issue by yann-combarnous** [AzureAD/microsoft-authentication-library-for-js#1138]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

Wiki, roadmap and news are outdated. MSAL 1.2 and 1.3 are still marked for September, when there is no sign of 1.2 getting out of beta.

## Expected behavior

It should be easier to understand where the project is at and is going to, by adding monthly news / update and updating wiki.

**Comment by sameerag** [comment]
@yann-combarnous A newsletter for timely announcements is something we have been considering for some time. cc @DarylThayil.

Regarding 1.2 release, we think we are close to it now as the betas are now tested well around and we have received great feedback from the community. We plan to announce it soon and wiki will be updated. We have been holding off the wiki updates for betas and planned it for the major release.
