### ISSUE TITLE
MSAL.js v2 GA checklist

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#1738]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description

Checklist of items that need to be completed for GA of MSAL.js v2.

## Priority

High

## Acceptance Criteria

Required:

- [x] Documentation on docs.microsoft.com
- [x] Quickstart on docs.microsoft.com
- [x] Documentation in Azure Portal
- [x] Quickstart in Azure Portal
- [x] Remove preview tags from all documentation
- [x] Update samples to use GA version
- [x] FAQ & Troubleshooting guide (public and internal for CSS)
- [x] Self-help for Azure Portal
- [x] Update reference documentation
- [x] Performance telemetry
- [x] Bug bash
- [x] Blog post
- [x] Update roadmaps
- [x] Release to the CDN

Nice to have:

- [ ] Powershell APIs for updating app registration
- [ ] Sovereign cloud testing

**Comment by sidhuko** [comment]
Perhaps you can clean up the bad practices and race conditions you create in your libraries by removing code which initialises in constructors and breaks the Single Responsibility Principle. Letting developers handle the hash callback is not a huge problem but your library smells of opinion and has terrible documentation. It needs drastic improvement:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/app/PublicClientApplication.ts#L108

**Comment by jasonnutter** [comment]
@sidhuko We have already decided to remove the automatic redirect response processing from the constructor, meaning applications using redirects need to call `handleRedirectPromise` in order to process the response. The code you linked to can probably be moved into that promise, we'll take a look at that.

Otherwise, if you have further constructive criticism or feedback (about the library, documentation, etc.), feel free to open a separate issue, thanks!
