### ISSUE TITLE
MSAL retry policy

### ISSUE THREAD

**Issue by aleknik** [AzureAD/microsoft-authentication-library-for-js#5128]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

What is the guidance on retry policy for MSAL node?

### Source

Internal (Microsoft)

## Spec

MSAL throws several types of exceptions: 

- base class is [AuthError](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/72fdd1fe926d72422caff139cf5abe2e31cef9fb/lib/msal-common/src/error/AuthError.ts#L25) 
- client errors come from the SDK itself [ClientAuthError](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/72fdd1fe926d72422caff139cf5abe2e31cef9fb/lib/msal-common/src/error/ClientAuthError.ts#L212)
- client configuration errors are a subclass of client errors [ClientConfigurationError](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/72fdd1fe926d72422caff139cf5abe2e31cef9fb/lib/msal-common/src/error/ClientConfigurationError.ts#L109)
- [ServerError](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/72fdd1fe926d72422caff139cf5abe2e31cef9fb/lib/msal-common/src/error/ServerError.ts#L11) is for when AAD (the service) returns an error as part of a 400 / 401 response. See [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes) for some of the AAD error codes. 
- [UiRequiredError](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/72fdd1fe926d72422caff139cf5abe2e31cef9fb/lib/msal-common/src/error/InteractionRequiredAuthError.ts#L42) for when interaction is required
- other errors which the library does not re-package. For example, if the request to AAD returns a 500 error ("server error"), MSAL will not catch this (?). Needs confirmation @Robbie-Microsoft 

## Retriable exceptions

- server responses which return with HTTP status codes 408 (unlikely to be seen here) , 429, 5xx 
Important: If a "retry-after" header is present, it must be observed (e.g. 500 error + Retry-After: 5)
- transient HTTP errors, such as the box losing connectivity temporarily (to test, just pull the internet cable out :) )
- in the future, some of the AAD exceptions, but for now we don't have this, so all other `ServerError`s should be seen as non-retry-able.

## Task list

- [x] analyze what exceptions occur if server returns 429, 500, 501 etc. 
- [x] identify other transient HTTP exceptions
- [x] ensure that the app developer can read the HttpStatus and Headers of exceptions, particularly for 429, 500 etc.
- [ ] create a simple retry policy as example / documentation 

CC @Robbie-Microsoft @jmprieur

**Comment by bgavrilMS** [comment]
Please see the .NET guidance here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Retry-Policy

**Comment by aleknik** [comment]
@bgavrilMS does msal-node implement the "retryOnceOn5xx" policy?

**Comment by bgavrilMS** [comment]
@aleknik - no, it does not. The `retryOnceOn5xx` seems to be implemented only in MSAL .NET and in hindsight it was a bad decision, because it interferes with retry policies set by others.

**Comment by aleknik** [comment]
Ok, so the recommendation is for clients to implement their own retry logic. I see .NET has a handy IsRetryable property on exception objects. Is this property present in JS exceptions and if not is there a plan to support it?

**Comment by bgavrilMS** [comment]
@aleknik - no, but @Robbie-Microsoft is looking into it. Let me try to spec this a bit (in the description). Please provide feedback on the plan.

**Comment by bgavrilMS** [comment]
Aside: @EmLauber @jasonnutter - do you know if claim challenges are extracted as part of UiRequiredError or ServerError? I did not see them anywhere in the code. Can MSAL.js handle claim challenges from ESTS?

**Comment by jasonnutter** [comment]
> Aside: @EmLauber Emily Lauber FTE @jasonnutter Jason Nutter FTE - do you know if claim challenges are extracted as part of UiRequiredError or ServerError? I did not see them anywhere in the code. Can MSAL.js handle claim challenges from ESTS?

Don't believe so, no. @tnorling @hectormmg can you confirm?
